import { useMemo, useState } from 'react';
import { competitors, quality, quotes, seasonality } from './data';
import { challengeRecommendation, recommend } from './engine';
import type { Controls, Objective, Risk, Scenario } from './types';

const money=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const pct=(n:number)=>`${n.toFixed(1)}%`;
function Tag({children,type='derived'}:{children:React.ReactNode;type?:string}){return <span className={`tag ${type}`}>{children}</span>}
function Control<T extends string>({label,value,items,onChange}:{label:string;value:T;items:T[];onChange:(x:T)=>void}){return <div className="control" aria-label={label}><div className="control-heading"><span>{label}</span><small>Choose one</small></div><div className="control-options">{items.map(x=><button type="button" key={x} className={x===value?'active':''} aria-pressed={x===value} onClick={()=>onChange(x)}>{x===value&&<span className="check" aria-hidden="true">✓</span>}{x}</button>)}</div></div>}
function Meter({value,label}:{value:number;label:string}){return <div className="meter"><div className="meter-head"><span>{label}</span><b>{value.toFixed(0)}/100</b></div><div className="track"><i style={{width:`${value}%`}} /></div></div>}

export default function App(){
 const [controls,setControls]=useState<Controls>({objective:'Balanced Growth',risk:'Balanced',scenario:'Base'}); const r=useMemo(()=>recommend(controls),[controls]); const challenge=useMemo(()=>challengeRecommendation(controls),[controls]);
 const update=<K extends keyof Controls>(key:K,value:Controls[K])=>setControls(c=>({...c,[key]:value}));
 return <main><header><div className="brand"><span className="dot"/> LUMEN <small>Germany market entry</small></div><Tag type="forecast">DATA-DRIVEN ESTIMATE</Tag></header>
 <section className="controls" aria-label="Configuration builder"><div className="controls-intro"><span className="eyebrow">CONFIGURATION BUILDER</span><p>Choose one option in each category to create a recommendation.</p></div><div className="control-groups"><Control label="Strategic objective" value={controls.objective} items={['Premium Brand','Balanced Growth','Fast Payback']} onChange={x=>update('objective',x as Objective)}/><Control label="Risk appetite" value={controls.risk} items={['Conservative','Balanced','Aggressive']} onChange={x=>update('risk',x as Risk)}/><Control label="Scenario" value={controls.scenario} items={['Base','Downside','Upside']} onChange={x=>update('scenario',x as Scenario)}/></div><div className="configuration-summary"><span className="summary-label">ACTIVE COMBINATION</span><strong>{controls.objective}</strong><i>+</i><strong>{controls.risk}</strong><i>+</i><strong>{controls.scenario}</strong></div></section>
 <section className="hero"><div className="recommendation"><Tag type="forecast">EXECUTIVE RECOMMENDATION</Tag><h1>Launch at <em>€{r.price.toFixed(2)}</em> with a focused, premium-functional entry.</h1><p className="lede">Prioritise <b>{r.target.name}</b> through {r.mix.sort((a,b)=>b.share-a.share).slice(0,2).map(x=>x.channel).join(' + ')}; open in <b>{r.cities.map(c=>c.name).join(', ')}</b> in <b>{r.launch.month}</b>.</p><p className="position">{r.position}</p><div className="why"><h3>Why this recommendation?</h3>{r.why.slice(0,3).map((x,i)=><p key={x}><b>0{i+1}</b>{x}<Tag>{i===0?'Observed test + derived score':i===1?'Observed survey + derived score':'Observed data + forecast'}</Tag></p>)}</div></div>
 <aside className="tradeoff"><div className="eyebrow">CMO ↔ CFO BALANCE · {Math.round(r.weights.cmo*100)}% / {Math.round(r.weights.cfo*100)}% WEIGHT</div><div className="cross" aria-label="All tested price options plotted by calculated CMO premium brand and CFO economics scores"><div className="axes"><span>CMO / premium brand score</span><span>CFO / economics score</span></div>{r.options.map(option=><div key={option.price} className={`bubble ${option.selected?'selected':'alternative'}`} style={{left:`${Math.max(9,Math.min(91,option.cmo))}%`,bottom:`${Math.max(10,Math.min(89,option.cfo))}%`}} aria-label={`${option.selected?'Selected strategy':'Alternative'} €${option.price.toFixed(2)}: CMO ${option.cmo.toFixed(0)}, CFO ${option.cfo.toFixed(0)}`}><b>{option.selected?'Selected':'Alternative'}</b><small>€{option.price.toFixed(2)}</small></div>)}</div><div className="option-legend">{r.options.map(option=><span key={option.price}><i className={option.selected?'selected':''}/>€{option.price.toFixed(2)} · CMO {option.cmo.toFixed(0)} / CFO {option.cfo.toFixed(0)}</span>)}</div><Meter label="CMO / premium brand score" value={r.cmo}/><Meter label="CFO / economics score" value={r.cfo}/><div className="confidence"><Tag type="assumption">CONFIDENCE & SCOPE</Tag><p>{r.confidence}</p><small>No German LUMEN sales exist. Values are transparent forecasts, not real-time predictions.</small></div></aside></section>
 <section className="kpis" aria-label="Selected scenario economics"><div><Tag type="forecast">FORECAST</Tag><b>{pct(r.acceptance)}</b><span>estimated acceptance / eligible prospect</span></div><div><Tag>DERIVED</Tag><b>{money(r.contribution)}</b><span>contribution / 1,000 acquired customers</span></div><div><Tag type="forecast">FORECAST</Tag><b>{money(r.expectedContribution)}</b><span>expected contribution / 1,000 eligible prospects</span></div><div><Tag type="observed">OBSERVED + ASSUMPTION</Tag><b>{money(r.cac)}</b><span>CAC proxy per acquired customer</span></div><div><Tag type="forecast">FORECAST</Tag><b>{r.ratio.toFixed(2)}×</b><span>estimated LTV:CAC</span></div><div><Tag type="forecast">FORECAST</Tag><b>{r.paybackUnits.toFixed(0)}</b><span>units to recover CAC</span></div></section>
 <section className="callout"><Tag type="assumption">DELIBERATE CHOICE</Tag><h2>{r.sacrifice}</h2><p>The alternative is visible in the CMO/CFO trade-off rather than concealed inside a single score.</p></section>
 <section className="challenge"><div className="section-title"><div><Tag type="assumption">STRESS TEST · ASSUMPTIONS</Tag><h2>Challenge the recommendation</h2></div><p>What would make the current decision stop being best?</p></div><div className="challenge-baseline"><b>Baseline</b><p>The current recommendation is to launch at €{challenge.baseline.price.toFixed(2)} in {challenge.baseline.launch.month} for the {challenge.baseline.target.name} segment.</p><p>The selected channel mix is {challenge.baseline.mix.map(x=>`${Math.round(x.share*100)}% ${x.channel}`).join(' and ')}. Under this baseline, LTV:CAC is {challenge.baseline.ratio.toFixed(2)}×, CAC is {money(challenge.baseline.cac)}, payback requires {challenge.baseline.paybackUnits.toFixed(0)} units, and expected contribution is {money(challenge.baseline.expectedContribution)} per 1,000 eligible prospects.</p></div><div className="stress-grid">{challenge.cases.map(x=><div className="stress-card" key={x.name}><b>{x.name}</b><p>{x.assumption}</p><p>The baseline selects {x.baseline}; under this stress, the model selects {x.stressed}. {x.impact}</p><Tag type={x.status==='Recommendation changes'?'assumption':x.status==='Recommendation weakens'?'observed':'derived'}>{x.status}</Tag></div>)}</div>{challenge.breakPoint&&<div className="breakpoint"><Tag type="assumption">BREAK POINT / FALLBACK</Tag><h3>{challenge.breakPoint.trigger}: €{challenge.breakPoint.fallbackPrice.toFixed(2)} becomes preferred</h3><p>{challenge.breakPoint.reason}</p></div>}<p className="caption">{challenge.why}</p></section>
 <section className="grid two"><article><div className="section-title"><div><Tag>DERIVED CALCULATION</Tag><h2>Price × channel economics</h2></div><p>All values stay channel-specific.</p></div><div className="table-wrap"><table><thead><tr><th>Channel</th><th>Mix</th><th>Acceptance</th><th>Net to LUMEN</th><th>Contribution</th><th>Margin</th></tr></thead><tbody>{r.priceRows.map(row=>{const mix=r.mix.find(x=>x.channel===row.channel)!;return <tr key={row.channel}><td>{row.channel}</td><td>{pct(mix.share*100)}</td><td>{pct(row.acceptance)}</td><td>€{row.net.toFixed(2)}</td><td>€{row.contribution.toFixed(2)}</td><td>{pct(row.margin)}</td></tr>})}</tbody></table></div><p className="caption">Tested price: €{r.price.toFixed(2)} only. No blended shelf price is used.</p></article>
 <article><div className="section-title"><div><Tag type="forecast">SCENARIO RANGE</Tag><h2>Stress test, not certainty</h2></div><p>Selected: {controls.scenario}</p></div><div className="scenario-list">{r.scenarios.map(s=><div key={s.scenario} className={s.scenario===controls.scenario?'selected':''}><h3>{s.scenario}</h3><p><b>{pct(s.acceptance)}</b> acceptance</p><p><b>{money(s.cac)}</b> CAC</p><p><b>{s.ratio.toFixed(2)}×</b> LTV:CAC</p><p><b>{s.payback.toFixed(0)}</b> units payback</p></div>)}</div><p className="caption">Assumptions: downside reduces acceptance/LTV and raises CAC; upside does the reverse.</p></article></section>
 <section className="grid evidence"><article><Tag type="observed">OBSERVED DATA</Tag><h2>First-wave city priority</h2>{r.cities.map((c,i)=><div className="rank" key={c.name}><b>0{i+1}</b><span>{c.name}<small>{c.n} survey responses · {(c.marketShare*100).toFixed(0)}% market share</small></span><i><em style={{width:`${c.score}%`}}/></i><strong>{c.score.toFixed(0)}</strong></div>)}<p className="caption">Score combines market share, regional growth, survey intent and frequency; samples are not national population estimates.</p></article>
 <article><Tag type="observed">OBSERVED DATA</Tag><h2>Competitive whitespace</h2><div className="competitors">{competitors.map(([name,pos,price,spend,note])=><div key={String(name)}><b>{name}</b><span>{pos}</span><strong>€{Number(price).toFixed(2)}</strong><small>{note}</small></div>)}</div><p className="caption">Historic benchmark by equivalent single-can channels; not a live price feed.</p></article>
 <article><Tag type="observed">QUAL + QUANT</Tag><h2>Customer evidence</h2>{quotes.map(([segment,quote,read])=><div className="quote" key={String(segment)}><b>{segment}</b><q>{quote}</q><small>{read}</small></div>)}</article></section>
 <section className="grid two"><article><Tag type="observed">PRICE SENSITIVITY</Tag><h2>Van Westendorp guardrail</h2><div className="price-scale"><span>€0.93<br/><small>too cheap</small></span><span>€1.43<br/><small>cheap</small></span><strong style={{left:`${(r.price-.5)/3.1*100}%`}}>€{r.price.toFixed(2)}<small>tested recommendation</small></strong><span>€2.21<br/><small>expensive</small></span><span>€2.81<br/><small>too expensive</small></span></div><p className="caption">300 German respondents; thresholds are survey averages. The engine selects only from tested prices.</p></article>
 <article><Tag type="derived">TIMING LOGIC</Tag><h2>Launch in {r.launch.month}</h2><div className="season">{seasonality.map(x=><i key={x.m} className={x.m===r.launch.month?'active':''} style={{height:`${x.v/1.6}px`}} title={`${x.m} demand index ${x.v}`}/>)}</div><p>{r.launch.reason}</p></article></section>
 <section className="memo"><Tag type="forecast">EXECUTIVE MEMO · GENERATED FROM THIS RECOMMENDATION</Tag><h2>Germany entry decision</h2><p>Launch LUMEN in {r.launch.month} at €{r.price.toFixed(2)}. Lead with {r.target.name} in {r.cities.map(c=>c.name).join(', ')} using a {r.mix.map(x=>`${Math.round(x.share*100)}% ${x.channel}`).join(' / ')} mix. This is a data-driven estimate based on German survey and price-test evidence, historical channel proxies and explicit scenarios. {r.sacrifice}</p></section>
 <footer><span>Evidence: 12 supplied exhibits · <b>no raw respondent PII included</b></span><span>Data quality: {quality.duplicateSalesRows} duplicate home-market sales rows flagged; {quality.historicalMarkets}</span></footer>
 </main>;
}
